  GNU nano 8.4                                                                   docker-compose.yml
services:
  web:
    image: httpd:2.4
    container_name: portfolio-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/local/apache2/htdocs/
      - ./certs:/usr/local/apache2/conf/certs/
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf

